### ISSUE TITLE
PA Review: User Authentification

### ISSUE THREAD

**Issue by Jayad25** [Jayad25/kidsy_fullstackproject#2]
User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect 
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

**Comment by jenvomo** [comment]
Difference in navbar styling:
- [x] Color of nav bar buttons 
- [x] Spacing of nav bar buttons
![screen shot 2018-12-14 at 2 37 01 pm](https://user-images.githubusercontent.com/39272166/50033584-f6369f00-ffad-11e8-8c68-1ce04fb316af.png)

![screen shot 2018-12-14 at 2 37 08 pm](https://user-images.githubusercontent.com/39272166/50033599-02226100-ffae-11e8-8024-8fe2d16f86da.png)

**Comment by jenvomo** [comment]
Kidsy:
![screen shot 2018-12-17 at 10 29 17 am](https://user-images.githubusercontent.com/39272166/50107138-a262ca80-01e6-11e9-9950-1b942a9846f8.png)
Etsy:
![screen shot 2018-12-17 at 10 29 20 am](https://user-images.githubusercontent.com/39272166/50107157-aa226f00-01e6-11e9-8d83-45b14dbeea36.png)
- [x] Reduce font weight of navbar links
- [x] Style logout button to match your "Sign in" button
![screen shot 2018-12-17 at 10 31 07 am](https://user-images.githubusercontent.com/39272166/50107231-e229b200-01e6-11e9-910f-b581df288df4.png)
- [x] Change button text from "sign in" to "Sign In" to match Etsy

**Comment by jenvomo** [comment]
- [x] Remove underline on hover of "Sign In", "Demo user", and "Logout" buttons

![screen shot 2018-12-17 at 4 29 50 pm](https://user-images.githubusercontent.com/39272166/50124342-056d5500-0219-11e9-85e5-faf9c006e5f9.png)
![screen shot 2018-12-17 at 4 29 59 pm](https://user-images.githubusercontent.com/39272166/50124348-0dc59000-0219-11e9-85b8-1afd6ed3d6c4.png)
- [x] Update fonts on modal to match Etsy
- [x] Update padding above "sign in to continue" to match Etsy
